# Generated by Django 4.1.1 on 2023-05-27 09:25

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('userId', models.CharField(default=mainapp.models.randomUserIdGeneration, max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.CharField(default=mainapp.models.randomPostIdGeneration, max_length=50, primary_key=True, serialize=False)),
                ('postDesc', models.CharField(max_length=50)),
                ('postImg', models.ImageField(null=True, upload_to='postImg/')),
                ('postDate', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
